export const environment = {
  production: true,
  appVersion: 'v8.0.25',
  USERDATA_KEY: 'authf649fc9a5f55',
  isMockEnabled: true,
  apiUrl: 'api',
  appThemeName: 'Metronic',
  appPurchaseUrl: 'https://1.envato.market/EA4JP',
  appHTMLIntegration: 'https://preview.keenthemes.com/metronic8/demo1/documentation/base/helpers/flex-layouts.html',
  appPreviewUrl: 'https://preview.keenthemes.com/metronic8/angular/demo1/',
  appPreviewAngularUrl: 'https://preview.keenthemes.com/metronic8/angular/demo1',
  appPreviewDocsUrl: 'https://preview.keenthemes.com/metronic8/angular/docs',
  appPreviewChangelogUrl:
    'https://preview.keenthemes.com/metronic8/angular/docs/changelog',
  // apiUrl: 'mysite.com/api'
  duction: true,
  BASE_URL:"http://"+location.hostname+":90/api/",
  LOGIN_URL:"http://"+location.hostname+":90/token",
  DISCIPLINE_URL:"http://"+location.hostname+":90/api/Disciplines/",
  DISCIPLINE_LEVEL_URL:"http://"+location.hostname+":90/api/DisciplineLevels/",
  COURSE_URL:"http://"+location.hostname+":90/api/Courses/",
  CLASSROOM_URL:"http://"+location.hostname+":90/api/Classrooms/",
  SCHOOL_URL: "http://"+location.hostname+":90/api/Schools/",
  PRESENCE_URL: "http://"+location.hostname+":90/api/Presences/",
  MEMBER_URL: "http://"+location.hostname+":90/api/Members/",
  SCHOOLYEAR_URL:"http://"+location.hostname+":90/api/AnneeScolaires/",
  MEMBER_PHOTO_PATH:"http://"+location.hostname+":90/images/members/",
  PERIODICITY_URL:"http://"+location.hostname+":90/api/Periodicity/",
};
